<?php

declare(strict_types=1);

namespace Live627\PhpCsFixer\CustomFixers;

use PhpCsFixer\AbstractFixer;
use PhpCsFixer\Fixer\ConfigurableFixerInterface;
use PhpCsFixer\Fixer\ConfigurableFixerTrait;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolver;
use PhpCsFixer\FixerConfiguration\FixerConfigurationResolverInterface;
use PhpCsFixer\FixerConfiguration\FixerOptionBuilder;
use PhpCsFixer\FixerDefinition\CodeSample;
use PhpCsFixer\FixerDefinition\FixerDefinition;
use PhpCsFixer\Tokenizer\Token;
use PhpCsFixer\Tokenizer\Tokens;

/**
 * Renames camelCase identifiers to snake_case.
 *
 * This fixer is considered risky because renaming identifiers can change
 * runtime behavior when code relies on dynamic variable access, reflection,
 * serialization, string-based references, or other forms of indirect access.
 *
 * The fixer currently supports:
 *
 * - Local variables
 * - Function and method parameters
 * - PHPDoc variable references
 *
 * The fixer intentionally skips:
 *
 * - Superglobals
 * - Variable variables
 * - Variables referenced by compact()
 * - Variables referenced by extract()
 * - Variables referenced by parse_str()
 * - User-configured exclusions
 *
 * Exclusions can be configured using:
 *
 * - exclude
 * - exclude_patterns
 *
 * Example:
 *
 * ```php
 * [
 *     'exclude' => [
 *         'smcFunc',
 *         'modSettings',
 *     ],
 *     'exclude_patterns' => [
 *         '/^txt[A-Z]/',
 *     ],
 * ]
 * ```
 *
 * Example transformation:
 *
 * ```php
 * $memberName = 1;
 * $currentUserId = 2;
 * ```
 *
 * becomes:
 *
 * ```php
 * $member_name = 1;
 * $current_user_id = 2;
 * ```
 *
 * @phpstan-type _AutogeneratedInputConfiguration array{
 *     exclude?: list<string>,
 *     exclude_patterns?: list<string>
 * }
 *
 * @phpstan-type _AutogeneratedComputedConfiguration array{
 *     exclude: list<string>,
 *     exclude_patterns: list<string>
 * }
 */
final class SnakeCaseIdentifiersFixer extends AbstractFixer implements ConfigurableFixerInterface
{
	use ConfigurableFixerTrait;
	/*****************
	 * Class constants
	 *****************/

	private const SUPERGLOBALS = [
		'$_GET' => true,
		'$_POST' => true,
		'$_REQUEST' => true,
		'$_COOKIE' => true,
		'$_FILES' => true,
		'$_SERVER' => true,
		'$_ENV' => true,
		'$_SESSION' => true,
		'$GLOBALS' => true,
	];

	/*********************
	 * Internal properties
	 *********************/

	/**
	 * Compiled exclusion matcher.
	 */
	private string $exclude_pattern = '';

	/****************
	 * Public methods
	 ****************/

	public function getPriority(): int
	{
		return 0;
	}

	public function isCandidate(Tokens $tokens): bool
	{
		return $tokens->isTokenKindFound(T_VARIABLE);
	}

	public function isRisky(): bool
	{
		return true;
	}

	public function getDefinition(): FixerDefinition
	{
		return new FixerDefinition(
			'Converts camelCase identifiers to snake_case.',
			[
				new CodeSample(
					"<?php\n\n\$memberName = 1;\n\$txtBirthday = 1;\n",
				),
				new CodeSample(
					"<?php\n\n\$memberName = 1;\n\$txtBirthday = 1;\n",
					[
						'exclude' => [
							'$memberName',
						],
					],
				),
				new CodeSample(
					"<?php\n\n\$memberName = 1;\n\$txtBirthday = 1;\n",
					[
						'exclude_patterns' => [
							'/^\$txt[A-Z]/',
						],
					],
				),
			],
			null,
			'Risky when variables are referenced dynamically through functions such as compact(), extract(), or parse_str().',
		);
	}

	/******************
	 * Internal methods
	 ******************/

	protected function createConfigurationDefinition(): FixerConfigurationResolverInterface
	{
		return new FixerConfigurationResolver([
			(new FixerOptionBuilder('exclude', 'Names to exclude.'))
				->setAllowedTypes(['array'])
				->setDefault([])
				->getOption(),
			(new FixerOptionBuilder('exclude_patterns', 'Patterns to exclude.'))
				->setAllowedTypes(['array'])
				->setDefault([])
				->getOption(),
		]);
	}

	/**
	 * Applies identifier renames to the token stream.
	 *
	 * @param SplFileInfo $file   The file being processed.
	 * @param Tokens      $tokens The token collection to modify.
	 */
	protected function applyFix(\SplFileInfo $file, Tokens $tokens): void
	{
		$renames = [];

		foreach ($tokens as $index => $token) {
			if (!$token->isGivenKind(T_VARIABLE)) {
				continue;
			}

			$name = $token->getContent();

			if (isset(self::SUPERGLOBALS[$name])) {
				continue;
			}

			if ($this->exclude_pattern !== '' && preg_match($this->exclude_pattern, $name)) {
				continue;
			}

			$snake = $renames[$name] ?? $this->convertName($name);

			if ($snake !== $name) {
				$renames[$name] = $snake;
			}
		}

		if ($renames === []) {
			return;
		}

		foreach ($tokens as $index => $token) {
			if ($token->isGivenKind(T_VARIABLE)) {
				$name = $token->getContent();

				if (isset($renames[$name])) {
					$tokens[$index] = new Token([
						T_VARIABLE,
						$renames[$name],
					]);
				}
			}

			if ($token->isGivenKind(T_DOC_COMMENT)) {
				$doc = preg_replace_callback(
					'/\$\w+\b/',
					static fn($var) => $renames[$var[0]] ?? $var[0],
					$token->getContent(),
				);

				$tokens[$index] = new Token([T_DOC_COMMENT, $doc]);
			}
		}
	}

	protected function configurePostNormalisation(): void
	{
		$patterns = [];

		// Reset state.
		$this->exclude_pattern = '';

		foreach ($this->configuration['exclude'] as $name) {
			$patterns[] = preg_quote($name, '~');
		}

		if ($patterns !== []) {
			$this->exclude_pattern = '~^(?:' . implode('|', $patterns) . ')$';
		}

		$patterns = [];

		foreach ($this->configuration['exclude_patterns'] as $pattern) {
			$patterns[] = trim($pattern, '/');
		}

		if ($patterns !== []) {
			$this->exclude_pattern .= ($this->exclude_pattern !== '' ? '|' : '~') . implode('|', $patterns);
		}

		if ($this->exclude_pattern !== '' && $this->exclude_pattern[-1] !== '~') {
			$this->exclude_pattern .= '~';
		}
	}

	/**
	 * Converts a camelCase or PascalCase identifier to snake_case.
	 *
	 * Examples:
	 *
	 * userName          => user_name
	 * memberID          => member_id
	 * parseHTTPResponse => parse_http_response
	 *
	 * @param string $string The input string in camelCase format.
	 *
	 * @return string The converted string in snake_case format.
	 */
	private function convertName(string $name): string
	{
		return strtolower(preg_replace('/(?<=[a-z0-9])[A-Z]|(?<=[A-Z])[A-Z](?=[a-z])/', '_$0', $name));
	}
}
